---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
  - job_name: prometheus-nginx-exporter
    scrape_interval: 10s
    static_configs:
      - targets: ["prometheus-nginx-exporter:9150"]

  - job_name: "nginx-fluentd"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:24231"]

