global:
  scrape_interval: 1m
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "nginx-exporter-prometheus"
    static_configs:
      - targets: ["nginx-exporter-prometheus:9113"]

  - job_name: "nginx-fluentd"
    static_configs:
      - targets: ["fluentd:24231"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "alertmanagers"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [https_2xx]
    static_configs:
      - targets:
        - https://apache1.homelab.lan
        - https://apache2.homelab.lan
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.109.229:9115

  - job_name: 'speedtest-exporter'
    scrape_interval: 1h
    scrape_timeout: 1m
    static_configs:
      - targets: ['speedtest-exporter:9798']

