---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:

rule_files:

scrape_configs:
  - job_name: "nginx-exporter-prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["nginx-exporter-prometheus:9113"]

  - job_name: "nginx-fluentd"
    scrape_interval: 10s
    static_configs:
      - targets: ["fluentd:24231"]

