---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
  - job_name: prometheus-nginx-exporter
    static_configs:
      - targets: ["prometheus-nginx-exporter:9150"]

  - job_name: "nginx-fluentd"
    static_configs:
      - targets: ["nginx-fluentd:24231"]

